"use client";

import { useEffect, useState } from "react";
import { Users, Filter, ArrowRight, Table as TableIcon, LayoutDashboard, Settings, Layout, Calendar, Trash2, ExternalLink } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";

interface Submission {
  _id: string;
  eventId: string;
  data: Record<string, any>;
  createdAt: string;
}

interface Event {
  _id: string;
  title: string;
}

export default function SubmissionsPage() {
  const [submissions, setSubmissions] = useState<Submission[]>([]);
  const [eventsMap, setEventsMap] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [subRes, eventRes] = await Promise.all([
          fetch("/api/submissions"),
          fetch("/api/events")
        ]);
        
        const subData = await subRes.json();
        const eventData = await eventRes.json();

        // Map event IDs to titles for display
        const eMap: Record<string, string> = {};
        eventData.forEach((e: Event) => eMap[e._id] = e.title);
        
        setSubmissions(subData);
        setEventsMap(eMap);
      } catch (err) {
         console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  return (
    <div className="min-h-screen bg-slate-50 flex">
      {/* Shared Admin Sidebar for Consistency */}
      <aside className="w-64 bg-white border-r border-slate-200 hidden lg:flex flex-col p-6 space-y-8 h-screen sticky top-0">
        <div className="flex items-center gap-3 text-indigo-600 font-bold text-xl px-2">
           <Layout className="w-8 h-8" />
           <span>Engagement AdHub</span>
        </div>

        <nav className="space-y-1">
          <Link href="/admin" className="flex items-center gap-3 px-4 py-3 text-slate-500 hover:bg-slate-50 rounded-xl font-medium transition-all group">
             <LayoutDashboard className="w-5 h-5" />
             <span>Events</span>
          </Link>
          <Link href="/admin/submissions" className="flex items-center gap-3 px-4 py-3 bg-indigo-50 text-indigo-600 rounded-xl font-medium transition-all">
             <Users className="w-5 h-5" />
             <span>Responses</span>
          </Link>
          <Link href="#" className="flex items-center gap-3 px-4 py-3 text-slate-500 hover:bg-slate-50 rounded-xl font-medium transition-all">
             <Settings className="w-5 h-5" />
             <span>Settings</span>
          </Link>
        </nav>
      </aside>

      <main className="flex-1 p-8 lg:p-12 overflow-y-auto">
        <header className="flex items-center justify-between mb-12">
           <div>
              <h1 className="text-3xl font-bold text-slate-900">Form Responses</h1>
              <p className="text-slate-500 mt-1">Track and manage every personalized ad generated by MRs</p>
           </div>
           
           <div className="flex items-center gap-3">
              <button className="flex items-center gap-2 bg-white border border-slate-200 text-slate-600 px-4 py-2.5 rounded-xl font-bold text-sm hover:bg-slate-50 transition-all">
                 <Filter className="w-4 h-4" />
                 <span>Filter Results</span>
              </button>
           </div>
        </header>

        {loading ? (
          <div className="space-y-4">
             {[1, 2, 3, 4, 5].map(i => (
               <div key={i} className="h-16 bg-slate-200 rounded-xl animate-pulse" />
             ))}
          </div>
        ) : (
          <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
             <table className="w-full text-left border-collapse">
                <thead className="bg-slate-50 border-b border-slate-100 font-bold text-[10px] uppercase tracking-widest text-slate-400">
                   <tr>
                      <th className="px-6 py-5">Event Name</th>
                      <th className="px-6 py-5">Submission ID</th>
                      <th className="px-6 py-5">Main Data (Preview)</th>
                      <th className="px-6 py-5">Date Submitted</th>
                      <th className="px-6 py-5 text-center">Actions</th>
                   </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                   {submissions.map((sub) => (
                     <motion.tr 
                       initial={{ opacity: 0 }}
                       animate={{ opacity: 1 }}
                       key={sub._id} 
                       className="hover:bg-slate-50/50 transition-all group"
                     >
                        <td className="px-6 py-5">
                           <div className="flex items-center gap-3">
                              <div className="w-8 h-8 bg-indigo-50 text-indigo-500 rounded-lg flex items-center justify-center font-black text-[10px]">AD</div>
                              <span className="text-sm font-bold text-slate-700">{eventsMap[sub.eventId] || "Deleted Event"}</span>
                           </div>
                        </td>
                        <td className="px-6 py-5">
                           <span className="text-xs font-mono text-slate-400">#{sub._id.slice(-6)}</span>
                        </td>
                        <td className="px-6 py-5">
                           <div className="flex items-center gap-2">
                             {/* Display first few keys of data */}
                             {Object.entries(sub.data).slice(0, 2).map(([key, value]: [string, any]) => (
                               <span key={key} className="text-xs px-2 py-1 bg-slate-100 rounded-md text-slate-600 font-medium">
                                 {key.replace("_", " ")}: {typeof value === 'string' && value.startsWith('http') ? '📸 Photo' : value}
                               </span>
                             ))}
                             {Object.keys(sub.data).length > 2 && <span className="text-[10px] text-slate-400 font-bold">+{Object.keys(sub.data).length - 2} more</span>}
                           </div>
                        </td>
                        <td className="px-6 py-5">
                           <div className="flex items-center gap-2 text-xs text-slate-500">
                              <Calendar className="w-3 h-3" />
                              {new Date(sub.createdAt).toLocaleString("en-US", {
                                month: "short",
                                day: "numeric",
                                year: "numeric",
                                hour: "2-digit",
                                minute: "2-digit",
                              })}
                           </div>
                        </td>
                        <td className="px-6 py-5 text-center">
                           <div className="flex items-center justify-center gap-2 opacity-0 group-hover:opacity-100 transition-all">
                              <Link 
                                href={`/v/${sub._id}`}
                                target="_blank"
                                className="p-2 text-indigo-500 hover:bg-indigo-50 rounded-lg transition-all"
                              >
                                 <ExternalLink className="w-4 h-4" />
                              </Link>
                              <button className="p-2 text-rose-500 hover:bg-rose-50 rounded-lg transition-all">
                                 <Trash2 className="w-4 h-4" />
                              </button>
                           </div>
                        </td>
                     </motion.tr>
                   ))}
                </tbody>
             </table>
             
             {submissions.length === 0 && (
               <div className="py-24 flex flex-col items-center justify-center text-center">
                  <TableIcon className="w-16 h-16 text-slate-100 mb-4" />
                  <h3 className="text-lg font-bold text-slate-900">No submissions yet</h3>
                  <p className="text-slate-500 max-w-xs mt-1">Once MRs start filling your forms, they will appear here with dynamic data mapping.</p>
               </div>
             )}
          </div>
        )}
      </main>
    </div>
  );
}
